<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="20" hostname="DESKTOP-FUGQNF4" name="org.rerun.Case2" tests="24" failures="2" timestamp="03 Feb 2023 05:40:37 GMT" time="0.073" errors="0">
  <testcase name="testc" time="0.003" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.002" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.004" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testd" time="0.000" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testc" time="0.013" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.005" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testa" time="0.003" classname="org.rerun.Case2"/>
  <testcase name="testd" time="0.002" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testc" time="0.005" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testc" time="0.002" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testc" time="0.002" classname="org.rerun.Case2">
    <failure type="java.lang.AssertionError" message="expected [nation] but found [country]">
      <![CDATA[java.lang.AssertionError: expected [nation] but found [country]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.rerun.Case2.testc(Case2.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testc -->
  <testcase name="testb" time="0.012" classname="org.rerun.Case2"/>
  <testcase name="testc" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testc -->
  <testcase name="testd" time="0.000" classname="org.rerun.Case2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.rerun.Case2.testd(Case2.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.009" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.001" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
  <testcase name="testd" time="0.002" classname="org.rerun.Case2">
    <skipped/>
  </testcase> <!-- testd -->
</testsuite> <!-- org.rerun.Case2 -->
